
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "16000:16000"
    depends_on:
      - mongo-seed
  mongo-seed:
    image: mongo:latest
    volumes:
      - C:\Users\marco\Desktop\UNI\EngWeb\ENGWEB2024-Normal\ENGWEB2024-Normal\ex1\ExameNormal\datasets\dataset.json:/datasets/dataset.json
    command: mongoimport --host mongodb -d contratos -c contratos --type json --file /datasets/dataset.json --jsonArray
